//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Med.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class history_login
    {
        public int Id { get; set; }
        public string userLogin { get; set; }
        public Nullable<bool> success { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
    }
}
