//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Med.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class login_history
    {
        public int code { get; set; }
        public string login { get; set; }
        public System.DateTime date { get; set; }
        public int success { get; set; }
    
        public virtual success_types success_types { get; set; }
    }
}
