//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Med.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MeLabEntities : DbContext
    {
        public MeLabEntities()
            : base("name=MeLabEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<analyzers> analyzers { get; set; }
        public virtual DbSet<countries> countries { get; set; }
        public virtual DbSet<insurance_companies> insurance_companies { get; set; }
        public virtual DbSet<patients> patients { get; set; }
        public virtual DbSet<patients_blood> patients_blood { get; set; }
        public virtual DbSet<provide_services> provide_services { get; set; }
        public virtual DbSet<services> services { get; set; }
        public virtual DbSet<social_types> social_types { get; set; }
        public virtual DbSet<statuses> statuses { get; set; }
        public virtual DbSet<user_types> user_types { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<history_login> history_login { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
